image: scrapinghub

script:
  - git restore-mtime
  - docker build -t spidermon:0.1 -f Dockerfile-testing .
  - docker run --rm spidermon:0.1 tox

notify:
  slack:
    webhook_url: $$SLACK_HOOK_URL
    username: 'drone'
    channel: '#spidermon'
    on_started: false
    on_success: false
    on_failure: true
