image: scrapinghub

script:
  - git restore-mtime
  - pip install -U tox==2.9.1
  - tox

notify:
  slack:
    webhook_url: $$SLACK_HOOK_URL
    username: 'drone'
    channel: '#spidermon'
    on_started: false
    on_success: false
    on_failure: true
